# -*- coding: utf-8 -*-
"""Весь текст сайта на трёх языках. Слова в {фигурных скобках} в заголовках подсвечиваются акцентом."""

LANGS = ["uz", "ru", "en"]
DEFAULT_LANG = "uz"
LANG_NAMES = {"uz": "O‘zbekcha", "ru": "Русский", "en": "English"}
OG_LOCALE = {"uz": "uz_UZ", "ru": "ru_RU", "en": "en_US"}

T = {}

# ───────────────────────────────────── RU ─────────────────────────────────────
T["ru"] = {
    "site": {
        "name": "hoolee",
        "tagline": "Студия автоматизации бизнеса и ИИ-оркестраторов",
        "city": "Ташкент, Узбекистан",
        "footer_note": "Студия разработки. Ташкент, Узбекистан.",
        "skip": "К содержимому",
        "menu": "Меню",
    },
    "nav": {"services": "Услуги", "cases": "Кейсы", "about": "О студии", "contact": "Связаться"},
    "cta": {"talk": "Обсудить проект", "cases": "Смотреть кейсы", "all_services": "Все услуги", "all_cases": "Все кейсы", "open": "Открыть кейс", "back": "Назад"},
    "home": {
        "title": "hoolee — автоматизация бизнеса и ИИ-оркестраторы в Ташкенте",
        "description": "Студия программистов в Ташкенте: автоматизируем бизнес-процессы, внедряем ИИ-агентов и оркестраторы, разрабатываем боты, интеграции и внутренние системы для компаний Узбекистана.",
        "eyebrow": "Студия разработки · Ташкент",
        "h1": ["Автоматизируем", "бизнес. Строим", "{ИИ-оркестраторы}."],
        "lead": "Берём рутину вашей компании и передаём её цепочке программ и ИИ-агентов. Люди остаются там, где нужно решение, а всё остальное делается само.",
        "scroll": "Листайте",
        "marquee": ["Автоматизация процессов", "ИИ-агенты", "Оркестрация", "Telegram-боты", "Интеграции", "CRM и ERP", "Внутренние системы", "Локальные LLM", "Веб-разработка"],
        "services_eyebrow": "Что мы делаем",
        "services_title": "Четыре направления, один результат: меньше ручной работы",
        "cases_eyebrow": "Кейсы",
        "cases_title": "Системы, которые мы уже построили",
        "cases_lead": "Два флагманских продукта показывают, как мы думаем: агенты, роли, проверка и человек в контуре решений.",
        "process_eyebrow": "Как мы работаем",
        "process_title": "От разговора до работающей системы",
        "principles_eyebrow": "Принципы",
        "principles_title": "Почему с нами спокойно",
        "faq_eyebrow": "Вопросы",
        "faq_title": "Частые вопросы",
        "cta_title": "Расскажите, что съедает время в вашей компании",
        "cta_lead": "Опишите задачу в двух словах. Ответим и предложим первый шаг.",
    },
    "services": {
        "title": "Услуги — автоматизация процессов, ИИ-агенты, разработка | hoolee",
        "description": "Автоматизация бизнес-процессов, ИИ-оркестраторы и агенты, разработка веб-систем, ботов и интеграций, внедрение и поддержка. Студия hoolee, Ташкент.",
        "h1": "Что мы {делаем}",
        "lead": "Мы работаем с бизнесом, где много повторяющихся операций: продажи, заявки, документы, склад, поддержка клиентов. Ниже то, что берём в работу.",
        "for_label": "Кому подходит",
        "gets_label": "Что вы получаете",
        "items": [
            {
                "id": "automation",
                "n": "01",
                "title": "Автоматизация бизнес-процессов",
                "short": "Находим повторяющуюся работу и превращаем её в надёжный автоматический процесс.",
                "for": "Компании, где менеджеры вручную переносят данные между таблицами, чатами и учётными системами.",
                "points": ["Аудит и карта процессов", "Интеграции между CRM, Google, Telegram, WhatsApp, учётными системами", "Автоматические отчёты, уведомления и напоминания", "Контроль ошибок и журнал действий"],
            },
            {
                "id": "ai",
                "n": "02",
                "title": "ИИ-оркестраторы и агенты",
                "short": "Цепочка ИИ-агентов с ролями: постановка, план, исполнение, проверка. Человек подтверждает важное.",
                "for": "Компании, где задачи сложнее одного шаблона: коммерческие предложения, разбор обращений, работа сразу нескольких отделов.",
                "points": ["Оркестратор с отделами и ролями агентов", "Подтверждения человеком там, где цена ошибки высока", "База знаний компании с поиском", "Учёт токенов и стоимости каждой задачи"],
            },
            {
                "id": "dev",
                "n": "03",
                "title": "Индивидуальная разработка",
                "short": "Веб-системы, кабинеты, Telegram-боты и Mini App, внутренние панели под ваш процесс.",
                "for": "Компании, которым не подходят готовые CRM и конструкторы, или которые упёрлись в их ограничения.",
                "points": ["Веб-приложения и админ-панели", "Telegram-боты и Mini App", "API и интеграции с внешними сервисами", "Аккуратный интерфейс на русском и узбекском"],
            },
            {
                "id": "support",
                "n": "04",
                "title": "Внедрение и поддержка",
                "short": "Запускаем систему, обучаем команду и сопровождаем, пока она не станет привычной частью работы.",
                "for": "Всем, кто не хочет остаться один на один с готовой системой.",
                "points": ["Настройка на вашей инфраструктуре или у нас", "Обучение сотрудников", "Мониторинг и исправление ошибок", "Развитие: новые процессы и отделы по мере роста"],
            },
        ],
        "industries_title": "Где это работает",
        "industries": ["Оптовая и розничная торговля", "Логистика и склад", "Клиники и услуги", "HoReCa", "Производство", "Образование"],
    },
    "process": [
        {"n": "01", "title": "Аудит", "text": "Разбираем, как работает компания сегодня, и находим процессы, которые дороже всего обходятся вручную."},
        {"n": "02", "title": "Прототип", "text": "Быстро собираем рабочий прототип на ваших данных. Вы видите результат, а не презентацию."},
        {"n": "03", "title": "Внедрение", "text": "Доводим до продакшена: интеграции, права доступа, журнал, обучение команды."},
        {"n": "04", "title": "Поддержка", "text": "Следим за работой, исправляем, добавляем новые сценарии по мере роста."},
    ],
    "principles": [
        {"title": "Человек в контуре", "text": "Агент готовит и проверяет, но важные действия подтверждает человек. Так ИИ не совершает необратимых ошибок."},
        {"title": "Ваши данные у вас", "text": "Можем развернуть систему на вашем сервере и подключить локальную языковую модель, чтобы данные не покидали компанию."},
        {"title": "Прозрачная стоимость", "text": "Понятные этапы и результат в каждом из них. Видно, за что вы платите и что получили."},
        {"title": "Без магии", "text": "Показываем, как система принимает решения: журнал, роли, стоимость каждого шага."},
    ],
    "faq": [
        {"q": "Что такое ИИ-оркестратор?", "a": "Это система, которая получает задачу и распределяет её между несколькими ИИ-агентами с разными ролями: один планирует, другие выполняют, третий проверяет результат. Важные шаги подтверждает человек. Так можно автоматизировать работу, которая не сводится к одному шаблону."},
        {"q": "С каких компаний в Ташкенте и Узбекистане вы работаете?", "a": "Мы делаем системы для малого и среднего бизнеса: торговля, логистика, клиники, HoReCa, производство. Работаем из Ташкента, проекты ведём на русском и узбекском языках, при необходимости на английском."},
        {"q": "Сколько стоит автоматизация?", "a": "Зависит от процесса. Мы начинаем с короткого аудита, после которого называем объём работ и стоимость по этапам. Оставьте заявку, и мы обсудим вашу задачу."},
        {"q": "Можно ли обойтись без внешних ИИ-сервисов?", "a": "Да. Систему можно развернуть на вашем сервере и подключить локальную языковую модель. Это дороже по железу, но данные не уходят за пределы компании."},
        {"q": "Как быстро можно получить первый результат?", "a": "Рабочий прототип на ваших данных мы обычно показываем после аудита, ещё до полной разработки. Точные сроки зависят от процесса и количества интеграций."},
    ],
    "cases": {
        "title": "Кейсы — Ark Core и Anton | hoolee",
        "description": "Два флагманских проекта студии hoolee: Ark Core, платформа мультиагентной оркестрации бизнес-процессов, и Anton, автономная IT-компания из ИИ-агентов.",
        "h1": "Кейсы",
        "lead": "Два собственных продукта. Они показывают, как мы строим системы из ИИ-агентов: с ролями, проверкой, памятью и контролем стоимости.",
        "ark": {
            "slug": "ark-core",
            "name": "Ark Core",
            "tag": "Оркестрация бизнес-процессов",
            "short": "Платформа, в которой задача проходит цепочку ИИ-агентов: оценка, план, отделы, исполнение, проверка, приём. Человек подтверждает важное.",
            "title": "Ark Core — платформа ИИ-оркестрации бизнес-процессов | hoolee",
            "description": "Ark Core: мультиагентная платформа, где задачи бизнеса проходят цепочку ИИ-агентов с проверкой и подтверждением человеком. Живое демо на вымышленных данных.",
            "h1": "Ark {Core}",
            "lead": "Задача ставится один раз. Дальше её ведёт цепочка ИИ-агентов, а человек подтверждает только то, что действительно важно.",
            "chain_title": "Как проходит задача",
            "chain": ["Оценка", "Оркестратор", "План", "Руководитель отдела", "Исполнитель", "Проверка", "Приёмка"],
            "demo_title": "Попробуйте сами",
            "demo_lead": "Это живое демо на вымышленных данных. Откройте чат в правом нижнем углу и запустите один из сценариев: простой вопрос, коммерческое предложение, задача для нескольких отделов или разбор жалобы клиента.",
            "demo_note": "Демо работает на заранее заготовленных сценариях, без внешних ИИ-сервисов. Все компании, сделки и суммы выдуманы.",
            "demo_open": "Открыть на весь экран",
            "demo_loading": "Загружаем демо…",
            "features_title": "Что внутри",
            "features": [
                {"t": "Отделы и роли", "d": "Юристы, финансы, маркетинг, продажи. Если задача не подходит ни одному отделу, платформа создаёт временный."},
                {"t": "Человек в контуре", "d": "Пайплайн действительно останавливается и ждёт вашего решения там, где цена ошибки высока."},
                {"t": "База знаний", "d": "Граф знаний компании с поиском. Агенты берут из него факты и правила."},
                {"t": "Учёт стоимости", "d": "Токены, стоимость и задержка каждого шага видны по каждой задаче."},
                {"t": "Журнал и права", "d": "Полный аудит действий, пользователи и роли доступа."},
                {"t": "Telegram и Mini App", "d": "Постановка задач и подтверждения прямо из мессенджера."},
            ],
            "stack_title": "Технологии",
            "stack": ["Python", "JavaScript", "PostgreSQL + pgvector", "Redis", "Docker", "Telegram Bot API", "Локальные и облачные LLM"],
            "cta": "Хотите такую систему для своей компании?",
        },
        "anton": {
            "slug": "anton",
            "name": "Anton",
            "tag": "Автономная IT-компания из ИИ-агентов",
            "short": "Ставите одну задачу, а над ней работает иерархия агентов, повторяющая структуру IT-компании: от диспетчера до QA и релиза.",
            "title": "Anton — IT-компания из ИИ-агентов | hoolee",
            "description": "Anton: платформа автономной оркестрации ИИ-агентов, повторяющая структуру IT-компании. Раунды, консенсус ревьюеров, база знаний и живая изометрическая симуляция офиса.",
            "h1": "{Anton}",
            "lead": "Целая IT-компания из ИИ-агентов под вашим управлением. Вы ставите высокоуровневую задачу, а внутри платформы над ней работают роли: диспетчер, продукт, техника, дизайн, исполнители, QA, безопасность, релиз.",
            "org_title": "Оргструктура как рантайм",
            "org": {"dispatcher": "Диспетчер", "cpo": "CPO · продукт", "cto": "CTO · техника", "design": "Дизайн", "squad": "Команды исполнителей", "qa": "QA", "security": "Безопасность", "release": "Релиз"},
            "org_lead": "Задача не решается за один проход. Она идёт итеративными раундами и завершается только после единогласного одобрения обязательных ревьюеров или срабатывания стоп-условия.",
            "features_title": "Ключевые идеи",
            "features": [
                {"t": "Раунды и консенсус", "d": "Работа идёт раундами. «Готово» ставится только при одобрении всех обязательных ревьюеров."},
                {"t": "Организационная память", "d": "Граф знаний хранит уроки. Правила, выученные на одной задаче, подмешиваются в другие."},
                {"t": "Надёжность", "d": "Журнал событий с восстановлением после сбоя. Некорректный ответ модели никогда не считается одобрением."},
                {"t": "Защита бюджета", "d": "Лимиты стоимости и запросов, повторы, размыкание цепи при серии ошибок."},
                {"t": "Живая симуляция", "d": "Изометрический офис, в котором видно, кто над чем работает, плюс админ-панель и граф знаний."},
                {"t": "Любая модель", "d": "Работает с облачными и локальными моделями через единый слой провайдеров."},
            ],
            "status_title": "Статус",
            "status": "Alpha. Ядро на C++ работает, интерфейсы в активной разработке. Материалы и показ по запросу.",
            "stack_title": "Технологии",
            "stack": ["C++20", "React", "PixiJS", "SQLite", "WebSocket", "Node.js", "Docker"],
            "cta": "Нужна оркестрация агентов под вашу задачу?",
        },
    },
    "about": {
        "title": "О студии hoolee — разработка и ИИ-автоматизация в Ташкенте",
        "description": "hoolee — студия программистов из Ташкента. Автоматизация бизнес-процессов, ИИ-агенты и оркестраторы, разработка систем для бизнеса Узбекистана.",
        "h1": "Студия, которая делает {рутину} автоматической",
        "lead": "hoolee — студия разработки из Ташкента. Мы автоматизируем бизнес-процессы и строим ИИ-оркестраторы. Под проект подключаем команду программистов нужного профиля.",
        "story_title": "Как мы думаем",
        "story": [
            "Большинство компаний теряют время не на сложных задачах, а на десятках мелких: перенести данные, напомнить, проверить, согласовать. Именно они лучше всего автоматизируются.",
            "Мы не продаём «ИИ ради ИИ». Сначала понимаем процесс, потом выбираем инструмент: где-то хватит обычного скрипта, где-то нужна цепочка агентов.",
            "Свои идеи мы проверяем на собственных продуктах, поэтому знаем, где системы ломаются на практике.",
        ],
        "founder_title": "Основатель",
        "founder_name": "Muhammadrizo Abdurazzoqov",
        "founder_role": "Software Engineer / ML Engineering / Data Science",
        "founder_text": "Проектирует системы из ИИ-агентов и отвечает за архитектуру каждого проекта студии.",
        "founder_photo": "Фото скоро",
        "values_title": "Чем мы занимаемся",
        "values": ["Автоматизация процессов", "ИИ-оркестраторы", "Разработка систем", "Внедрение и поддержка"],
    },
    "contact": {
        "title": "Связаться с hoolee — обсудить проект автоматизации",
        "description": "Оставьте заявку студии hoolee: расскажите о задаче, и мы предложим первый шаг. Ташкент, Узбекистан.",
        "h1": "Расскажите о вашей {задаче}",
        "lead": "Пару предложений о том, что нужно автоматизировать. Отвечаем в рабочее время.",
        "location": "Ташкент, Узбекистан",
    },
    "form": {
        "title": "Связаться с нами",
        "name": "Имя",
        "company": "Компания",
        "contact": "Телефон или Telegram",
        "message": "Что нужно автоматизировать?",
        "message_ph": "Например: менеджеры вручную переносят заявки из Telegram в таблицу…",
        "step2": "Как отправить?",
        "step2_hint": "Выберите удобный способ. Данные никуда не уйдут, пока вы не нажмёте одну из кнопок.",
        "telegram": "Отправить через Telegram",
        "email": "Отправить по email",
        "sending": "Отправляем…",
        "ok": "Заявка отправлена. Мы свяжемся с вами.",
        "err": "Не удалось отправить. Попробуйте ещё раз или выберите другой способ.",
        "required": "Заполните имя, контакт и описание задачи.",
        "email_note": "Откроется ваша почтовая программа с готовым письмом.",
        "subject": "Заявка с сайта hoolee",
    },
    "footer": {"pages": "Страницы", "contact": "Контакты", "rights": "Все права защищены"},
    "not_found": {"title": "Страница не найдена", "text": "Такой страницы нет. Вернитесь на главную.", "home": "На главную"},
}

# ───────────────────────────────────── EN ─────────────────────────────────────
T["en"] = {
    "site": {
        "name": "hoolee",
        "tagline": "Business automation and AI orchestration studio",
        "city": "Tashkent, Uzbekistan",
        "footer_note": "Software studio. Tashkent, Uzbekistan.",
        "skip": "Skip to content",
        "menu": "Menu",
    },
    "nav": {"services": "Services", "cases": "Cases", "about": "About", "contact": "Contact"},
    "cta": {"talk": "Discuss a project", "cases": "See our cases", "all_services": "All services", "all_cases": "All cases", "open": "Open case", "back": "Back"},
    "home": {
        "title": "hoolee — business automation and AI orchestrators in Tashkent",
        "description": "A software studio in Tashkent: we automate business processes, deploy AI agents and orchestrators, and build bots, integrations and internal systems for companies in Uzbekistan.",
        "eyebrow": "Software studio · Tashkent",
        "h1": ["We automate", "business. We build", "{AI orchestrators}."],
        "lead": "We take the routine work of your company and hand it to a chain of programs and AI agents. People stay where a decision is needed, and the rest runs by itself.",
        "scroll": "Scroll",
        "marquee": ["Process automation", "AI agents", "Orchestration", "Telegram bots", "Integrations", "CRM and ERP", "Internal systems", "Local LLMs", "Web development"],
        "services_eyebrow": "What we do",
        "services_title": "Four directions, one result: less manual work",
        "cases_eyebrow": "Cases",
        "cases_title": "Systems we have already built",
        "cases_lead": "Two flagship products show how we think: agents, roles, review, and a human in the decision loop.",
        "process_eyebrow": "How we work",
        "process_title": "From a conversation to a working system",
        "principles_eyebrow": "Principles",
        "principles_title": "Why working with us is calm",
        "faq_eyebrow": "Questions",
        "faq_title": "Frequently asked questions",
        "cta_title": "Tell us what eats your team's time",
        "cta_lead": "Describe the task in a few words. We will reply with a first step.",
    },
    "services": {
        "title": "Services — process automation, AI agents, development | hoolee",
        "description": "Business process automation, AI orchestrators and agents, custom web systems, bots and integrations, rollout and support. hoolee studio, Tashkent.",
        "h1": "What we {do}",
        "lead": "We work with businesses full of repeating operations: sales, requests, documents, warehouse, customer support. Here is what we take on.",
        "for_label": "Who it is for",
        "gets_label": "What you get",
        "items": [
            {
                "id": "automation",
                "n": "01",
                "title": "Business process automation",
                "short": "We find repetitive work and turn it into a reliable automatic process.",
                "for": "Companies where managers copy data by hand between spreadsheets, chats and accounting systems.",
                "points": ["Process audit and map", "Integrations between CRM, Google, Telegram, WhatsApp and accounting systems", "Automatic reports, notifications and reminders", "Error control and an action log"],
            },
            {
                "id": "ai",
                "n": "02",
                "title": "AI orchestrators and agents",
                "short": "A chain of AI agents with roles: intake, plan, execution, review. A human approves what matters.",
                "for": "Companies whose tasks go beyond a single template: commercial proposals, complaint handling, work that spans several departments.",
                "points": ["Orchestrator with departments and agent roles", "Human approval where a mistake is costly", "Company knowledge base with search", "Token and cost tracking for every task"],
            },
            {
                "id": "dev",
                "n": "03",
                "title": "Custom development",
                "short": "Web systems, portals, Telegram bots and Mini Apps, internal panels built around your process.",
                "for": "Companies that do not fit off-the-shelf CRMs and builders, or have hit their limits.",
                "points": ["Web applications and admin panels", "Telegram bots and Mini Apps", "APIs and third-party integrations", "Clean interfaces in Russian and Uzbek"],
            },
            {
                "id": "support",
                "n": "04",
                "title": "Rollout and support",
                "short": "We launch the system, train your team, and stay with it until it becomes a normal part of work.",
                "for": "Anyone who does not want to be left alone with a finished system.",
                "points": ["Setup on your infrastructure or ours", "Staff training", "Monitoring and bug fixing", "Growth: new processes and departments as you scale"],
            },
        ],
        "industries_title": "Where it works",
        "industries": ["Wholesale and retail", "Logistics and warehousing", "Clinics and services", "HoReCa", "Manufacturing", "Education"],
    },
    "process": [
        {"n": "01", "title": "Audit", "text": "We study how the company works today and find the processes that cost the most when done by hand."},
        {"n": "02", "title": "Prototype", "text": "We quickly build a working prototype on your data. You see a result, not a slide deck."},
        {"n": "03", "title": "Rollout", "text": "We take it to production: integrations, access rights, logging, team training."},
        {"n": "04", "title": "Support", "text": "We watch it run, fix issues and add new scenarios as you grow."},
    ],
    "principles": [
        {"title": "Human in the loop", "text": "An agent prepares and checks, but important actions are confirmed by a person. AI never makes irreversible mistakes on its own."},
        {"title": "Your data stays yours", "text": "We can deploy the system on your server with a local language model so data never leaves the company."},
        {"title": "Transparent pricing", "text": "Clear stages with a result in each one. You see what you pay for and what you received."},
        {"title": "No magic", "text": "We show how the system decides: log, roles and the cost of every step."},
    ],
    "faq": [
        {"q": "What is an AI orchestrator?", "a": "It is a system that receives a task and distributes it among several AI agents with different roles: one plans, others execute, another reviews the result. A human confirms the important steps. It lets you automate work that cannot be reduced to a single template."},
        {"q": "What kind of companies in Tashkent and Uzbekistan do you work with?", "a": "We build systems for small and medium businesses: trade, logistics, clinics, HoReCa and manufacturing. We work from Tashkent and run projects in Russian and Uzbek, and in English when needed."},
        {"q": "How much does automation cost?", "a": "It depends on the process. We start with a short audit, after which we name the scope and the cost by stages. Leave a request and we will discuss your task."},
        {"q": "Can it work without external AI services?", "a": "Yes. The system can be deployed on your server with a local language model. It needs more hardware, but data does not leave the company."},
        {"q": "How fast can we see a first result?", "a": "We usually show a working prototype on your data right after the audit, before full development. Exact timing depends on the process and the number of integrations."},
    ],
    "cases": {
        "title": "Cases — Ark Core and Anton | hoolee",
        "description": "Two flagship projects by hoolee: Ark Core, a multi-agent business process orchestration platform, and Anton, an autonomous IT company made of AI agents.",
        "h1": "Cases",
        "lead": "Two products of our own. They show how we build systems out of AI agents: with roles, review, memory and cost control.",
        "ark": {
            "slug": "ark-core",
            "name": "Ark Core",
            "tag": "Business process orchestration",
            "short": "A platform where a task passes through a chain of AI agents: assessment, plan, departments, execution, review, acceptance. A human confirms what matters.",
            "title": "Ark Core — AI business process orchestration platform | hoolee",
            "description": "Ark Core: a multi-agent platform where business tasks pass through a chain of AI agents with review and human approval. Live demo on fictional data.",
            "h1": "Ark {Core}",
            "lead": "A task is set once. Then a chain of AI agents carries it through, and a person confirms only what really matters.",
            "chain_title": "How a task moves",
            "chain": ["Assessment", "Orchestrator", "Plan", "Department head", "Executor", "Review", "Acceptance"],
            "demo_title": "Try it yourself",
            "demo_lead": "This is a live demo on fictional data. Open the chat in the bottom-right corner and run a scenario: a simple question, a commercial proposal, a multi-department task or a customer complaint.",
            "demo_note": "The demo runs on pre-written scenarios with no external AI services. All companies, deals and amounts are fictional.",
            "demo_open": "Open full screen",
            "demo_loading": "Loading demo…",
            "features_title": "What is inside",
            "features": [
                {"t": "Departments and roles", "d": "Legal, finance, marketing, sales. If a task fits no department, the platform creates a temporary one."},
                {"t": "Human in the loop", "d": "The pipeline genuinely pauses and waits for your decision where a mistake is costly."},
                {"t": "Knowledge base", "d": "A company knowledge graph with search. Agents draw facts and rules from it."},
                {"t": "Cost tracking", "d": "Tokens, cost and latency of every step are visible for every task."},
                {"t": "Audit and access", "d": "A full action audit, users and access roles."},
                {"t": "Telegram and Mini App", "d": "Set tasks and approve results right from the messenger."},
            ],
            "stack_title": "Technology",
            "stack": ["Python", "JavaScript", "PostgreSQL + pgvector", "Redis", "Docker", "Telegram Bot API", "Local and cloud LLMs"],
            "cta": "Want a system like this for your company?",
        },
        "anton": {
            "slug": "anton",
            "name": "Anton",
            "tag": "An autonomous IT company of AI agents",
            "short": "You set one task and a hierarchy of agents mirroring an IT company works on it: from dispatcher to QA and release.",
            "title": "Anton — an IT company made of AI agents | hoolee",
            "description": "Anton: an autonomous AI agent orchestration platform that mirrors the structure of an IT company. Rounds, reviewer consensus, a knowledge base and a live isometric office simulation.",
            "h1": "{Anton}",
            "lead": "A whole IT company of AI agents under your control. You set a high-level task, and inside the platform roles work on it: dispatcher, product, engineering, design, executors, QA, security, release.",
            "org_title": "Org structure as a runtime",
            "org": {"dispatcher": "Dispatcher", "cpo": "CPO · product", "cto": "CTO · engineering", "design": "Design", "squad": "Executor squads", "qa": "QA", "security": "Security", "release": "Release"},
            "org_lead": "A task is not solved in one pass. It moves through iterative rounds and finishes only after unanimous approval from the mandatory reviewers, or when a stop condition fires.",
            "features_title": "Key ideas",
            "features": [
                {"t": "Rounds and consensus", "d": "Work proceeds in rounds. “Done” is set only when all mandatory reviewers approve."},
                {"t": "Organizational memory", "d": "A knowledge graph stores lessons. Rules learned on one task are mixed into others."},
                {"t": "Reliability", "d": "An event log with crash recovery. A malformed model answer is never treated as approval."},
                {"t": "Budget protection", "d": "Cost and rate limits, retries, and a circuit breaker on repeated failures."},
                {"t": "Live simulation", "d": "An isometric office where you see who works on what, plus an admin panel and a knowledge graph."},
                {"t": "Any model", "d": "Works with cloud and local models through a single provider layer."},
            ],
            "status_title": "Status",
            "status": "Alpha. The C++ core works, interfaces are under active development. Materials and a walkthrough on request.",
            "stack_title": "Technology",
            "stack": ["C++20", "React", "PixiJS", "SQLite", "WebSocket", "Node.js", "Docker"],
            "cta": "Need agent orchestration for your task?",
        },
    },
    "about": {
        "title": "About hoolee — software and AI automation studio in Tashkent",
        "description": "hoolee is a software studio from Tashkent. Business process automation, AI agents and orchestrators, and systems for businesses in Uzbekistan.",
        "h1": "A studio that makes {routine} automatic",
        "lead": "hoolee is a software studio from Tashkent. We automate business processes and build AI orchestrators. For each project we bring in developers with the right profile.",
        "story_title": "How we think",
        "story": [
            "Most companies lose time not on hard tasks but on dozens of small ones: copy data, remind, check, approve. Those are exactly what automates best.",
            "We do not sell “AI for the sake of AI”. We understand the process first, then pick the tool: sometimes a plain script is enough, sometimes you need a chain of agents.",
            "We test our ideas on products of our own, so we know where systems break in practice.",
        ],
        "founder_title": "Founder",
        "founder_name": "Muhammadrizo Abdurazzoqov",
        "founder_role": "Software Engineer / ML Engineering / Data Science",
        "founder_text": "Designs AI agent systems and is responsible for the architecture of every studio project.",
        "founder_photo": "Photo soon",
        "values_title": "What we do",
        "values": ["Process automation", "AI orchestrators", "Systems development", "Rollout and support"],
    },
    "contact": {
        "title": "Contact hoolee — discuss an automation project",
        "description": "Send a request to hoolee studio: tell us about your task and we will propose a first step. Tashkent, Uzbekistan.",
        "h1": "Tell us about your {task}",
        "lead": "A couple of sentences about what needs automating. We reply during working hours.",
        "location": "Tashkent, Uzbekistan",
    },
    "form": {
        "title": "Contact us",
        "name": "Name",
        "company": "Company",
        "contact": "Phone or Telegram",
        "message": "What needs automating?",
        "message_ph": "For example: managers copy requests from Telegram into a spreadsheet by hand…",
        "step2": "How would you like to send it?",
        "step2_hint": "Choose a way. Nothing is sent until you press one of the buttons.",
        "telegram": "Send via Telegram",
        "email": "Send by email",
        "sending": "Sending…",
        "ok": "Request sent. We will get back to you.",
        "err": "Could not send. Try again or choose another way.",
        "required": "Please fill in your name, contact and task description.",
        "email_note": "Your mail app will open with a ready-made message.",
        "subject": "Request from hoolee website",
    },
    "footer": {"pages": "Pages", "contact": "Contact", "rights": "All rights reserved"},
    "not_found": {"title": "Page not found", "text": "There is no such page. Go back to the home page.", "home": "Home"},
}

# ───────────────────────────────────── UZ ─────────────────────────────────────
T["uz"] = {
    "site": {
        "name": "hoolee",
        "tagline": "Biznesni avtomatlashtirish va AI orkestratorlar studiyasi",
        "city": "Toshkent, O‘zbekiston",
        "footer_note": "Dasturiy ishlanmalar studiyasi. Toshkent, O‘zbekiston.",
        "skip": "Kontentga o‘tish",
        "menu": "Menyu",
    },
    "nav": {"services": "Xizmatlar", "cases": "Keyslar", "about": "Studiya haqida", "contact": "Bog‘lanish"},
    "cta": {"talk": "Loyihani muhokama qilish", "cases": "Keyslarni ko‘rish", "all_services": "Barcha xizmatlar", "all_cases": "Barcha keyslar", "open": "Keysni ochish", "back": "Orqaga"},
    "home": {
        "title": "hoolee — Toshkentda biznesni avtomatlashtirish va AI orkestratorlar",
        "description": "Toshkentdagi dasturchilar studiyasi: biznes jarayonlarini avtomatlashtiramiz, AI agentlar va orkestratorlarni joriy qilamiz, O‘zbekiston kompaniyalari uchun botlar, integratsiyalar va ichki tizimlar yaratamiz.",
        "eyebrow": "Dasturiy studiya · Toshkent",
        "h1": ["Biznesni", "avtomatlashtiramiz.", "{AI orkestratorlar} yaratamiz."],
        "lead": "Kompaniyangizdagi doimiy takrorlanadigan ishni dasturlar va AI agentlar zanjiriga topshiramiz. Odamlar qaror kerak bo‘lgan joyda qoladi, qolgani o‘zi bajariladi.",
        "scroll": "Pastga",
        "marquee": ["Jarayonlarni avtomatlashtirish", "AI agentlar", "Orkestratsiya", "Telegram botlar", "Integratsiyalar", "CRM va ERP", "Ichki tizimlar", "Lokal LLM", "Veb-ishlanma"],
        "services_eyebrow": "Nima qilamiz",
        "services_title": "To‘rt yo‘nalish, bitta natija: qo‘lda ish kamayadi",
        "cases_eyebrow": "Keyslar",
        "cases_title": "Biz allaqachon yaratgan tizimlar",
        "cases_lead": "Ikki asosiy mahsulot bizning yondashuvimizni ko‘rsatadi: agentlar, rollar, tekshiruv va qaror aylanmasida inson.",
        "process_eyebrow": "Qanday ishlaymiz",
        "process_title": "Suhbatdan ishlaydigan tizimgacha",
        "principles_eyebrow": "Tamoyillar",
        "principles_title": "Biz bilan nega xotirjam",
        "faq_eyebrow": "Savollar",
        "faq_title": "Ko‘p beriladigan savollar",
        "cta_title": "Jamoangizning vaqtini nima yeyotganini ayting",
        "cta_lead": "Vazifani ikki-uch so‘z bilan yozing. Javob berib, birinchi qadamni taklif qilamiz.",
    },
    "services": {
        "title": "Xizmatlar — jarayonlarni avtomatlashtirish, AI agentlar, ishlanma | hoolee",
        "description": "Biznes jarayonlarini avtomatlashtirish, AI orkestratorlar va agentlar, veb-tizimlar, botlar va integratsiyalar ishlab chiqish, joriy etish va qo‘llab-quvvatlash. hoolee studiyasi, Toshkent.",
        "h1": "Biz nima {qilamiz}",
        "lead": "Takrorlanadigan amallar ko‘p bo‘lgan biznes bilan ishlaymiz: savdo, arizalar, hujjatlar, ombor, mijozlarni qo‘llab-quvvatlash. Quyida biz olib boradigan ishlar.",
        "for_label": "Kimga mos",
        "gets_label": "Siz nima olasiz",
        "items": [
            {
                "id": "automation",
                "n": "01",
                "title": "Biznes jarayonlarini avtomatlashtirish",
                "short": "Takrorlanadigan ishni topib, uni ishonchli avtomatik jarayonga aylantiramiz.",
                "for": "Menejerlar ma’lumotlarni jadval, chat va hisob tizimlari orasida qo‘lda ko‘chiradigan kompaniyalar.",
                "points": ["Jarayonlar auditi va xaritasi", "CRM, Google, Telegram, WhatsApp va hisob tizimlari integratsiyasi", "Avtomatik hisobotlar, bildirishnomalar va eslatmalar", "Xatolarni nazorat qilish va harakatlar jurnali"],
            },
            {
                "id": "ai",
                "n": "02",
                "title": "AI orkestratorlar va agentlar",
                "short": "Rollarga ega AI agentlar zanjiri: qabul, reja, bajarish, tekshiruv. Muhim narsani inson tasdiqlaydi.",
                "for": "Vazifalari bitta shablonga sig‘maydigan kompaniyalar: tijorat takliflari, murojaatlarni ko‘rib chiqish, bir necha bo‘lim ishi.",
                "points": ["Bo‘limlar va agent rollari bilan orkestrator", "Xato qimmatga tushadigan joyda inson tasdig‘i", "Qidiruvli kompaniya bilimlar bazasi", "Har bir vazifa uchun token va xarajat hisobi"],
            },
            {
                "id": "dev",
                "n": "03",
                "title": "Individual ishlanma",
                "short": "Veb-tizimlar, kabinetlar, Telegram botlar va Mini App, sizning jarayoningizga mos ichki panellar.",
                "for": "Tayyor CRM va konstruktorlar to‘g‘ri kelmaydigan yoki ularning cheklovlariga tiralgan kompaniyalar.",
                "points": ["Veb-ilovalar va admin-panellar", "Telegram botlar va Mini App", "API va tashqi xizmatlar bilan integratsiya", "Rus va o‘zbek tilidagi qulay interfeys"],
            },
            {
                "id": "support",
                "n": "04",
                "title": "Joriy etish va qo‘llab-quvvatlash",
                "short": "Tizimni ishga tushiramiz, jamoani o‘rgatamiz va u odatiy ishga aylanguncha yonida bo‘lamiz.",
                "for": "Tayyor tizim bilan yolg‘iz qolishni istamaydigan har bir kishi.",
                "points": ["Sizning yoki bizning infratuzilmada sozlash", "Xodimlarni o‘qitish", "Monitoring va xatolarni tuzatish", "O‘sish bilan yangi jarayon va bo‘limlar qo‘shish"],
            },
        ],
        "industries_title": "Qayerda ishlaydi",
        "industries": ["Ulgurji va chakana savdo", "Logistika va ombor", "Klinikalar va xizmatlar", "HoReCa", "Ishlab chiqarish", "Ta’lim"],
    },
    "process": [
        {"n": "01", "title": "Audit", "text": "Kompaniya bugun qanday ishlashini o‘rganamiz va qo‘lda bajarilganda eng qimmat jarayonlarni topamiz."},
        {"n": "02", "title": "Prototip", "text": "Sizning ma’lumotlaringizda tez ishlaydigan prototip yig‘amiz. Siz taqdimotni emas, natijani ko‘rasiz."},
        {"n": "03", "title": "Joriy etish", "text": "Ishga tushiramiz: integratsiyalar, kirish huquqlari, jurnal, jamoani o‘qitish."},
        {"n": "04", "title": "Qo‘llab-quvvatlash", "text": "Ishlashini kuzatamiz, xatolarni tuzatamiz va o‘sish bilan yangi stsenariylar qo‘shamiz."},
    ],
    "principles": [
        {"title": "Aylanmada inson", "text": "Agent tayyorlaydi va tekshiradi, muhim harakatlarni esa inson tasdiqlaydi. Shunda AI qaytarib bo‘lmas xato qilmaydi."},
        {"title": "Ma’lumot sizda qoladi", "text": "Tizimni sizning serveringizda lokal til modeli bilan joylashtira olamiz, ma’lumotlar kompaniyadan chiqmaydi."},
        {"title": "Shaffof narx", "text": "Har bir bosqichda natija bor. Nima uchun to‘layotganingiz va nima olganingiz ko‘rinib turadi."},
        {"title": "Sehrsiz", "text": "Tizim qaror qanday qabul qilishini ko‘rsatamiz: jurnal, rollar va har bir qadam narxi."},
    ],
    "faq": [
        {"q": "AI orkestrator nima?", "a": "Bu vazifani qabul qilib, uni turli rollardagi bir necha AI agent o‘rtasida taqsimlaydigan tizim: biri rejalashtiradi, boshqalari bajaradi, yana biri natijani tekshiradi. Muhim qadamlarni inson tasdiqlaydi. Bitta shablonga sig‘maydigan ishni avtomatlashtirish shunday amalga oshadi."},
        {"q": "Toshkent va O‘zbekistonda qanday kompaniyalar bilan ishlaysiz?", "a": "Kichik va o‘rta biznes uchun tizimlar yaratamiz: savdo, logistika, klinikalar, HoReCa, ishlab chiqarish. Toshkentdan ishlaymiz, loyihalarni rus va o‘zbek tilida, kerak bo‘lsa ingliz tilida olib boramiz."},
        {"q": "Avtomatlashtirish qancha turadi?", "a": "Jarayonga bog‘liq. Qisqa auditdan boshlaymiz, undan keyin ish hajmi va narxni bosqichlar bo‘yicha aytamiz. Ariza qoldiring, vazifangizni muhokama qilamiz."},
        {"q": "Tashqi AI xizmatlarisiz ishlasa bo‘ladimi?", "a": "Ha. Tizimni sizning serveringizda lokal til modeli bilan joylashtirish mumkin. Bu uskunaga ko‘proq xarajat talab qiladi, lekin ma’lumotlar kompaniyadan chiqmaydi."},
        {"q": "Birinchi natijani qanchalik tez ko‘rish mumkin?", "a": "Odatda auditdan keyin, to‘liq ishlanmadan oldin, sizning ma’lumotlaringizda ishlaydigan prototipni ko‘rsatamiz. Aniq muddat jarayon va integratsiyalar soniga bog‘liq."},
    ],
    "cases": {
        "title": "Keyslar — Ark Core va Anton | hoolee",
        "description": "hoolee studiyasining ikkita asosiy loyihasi: Ark Core, biznes jarayonlarini multi-agent orkestratsiya qilish platformasi va Anton, AI agentlardan iborat avtonom IT-kompaniya.",
        "h1": "Keyslar",
        "lead": "Ikkita o‘z mahsulotimiz. Ular AI agentlardan tizimlarni qanday qurishimizni ko‘rsatadi: rollar, tekshiruv, xotira va xarajat nazorati bilan.",
        "ark": {
            "slug": "ark-core",
            "name": "Ark Core",
            "tag": "Biznes jarayonlari orkestratsiyasi",
            "short": "Vazifa AI agentlar zanjiridan o‘tadigan platforma: baholash, reja, bo‘limlar, bajarish, tekshiruv, qabul. Muhim narsani inson tasdiqlaydi.",
            "title": "Ark Core — biznes jarayonlarini AI orkestratsiya qilish platformasi | hoolee",
            "description": "Ark Core: biznes vazifalari AI agentlar zanjiridan o‘tadigan, tekshiruv va inson tasdig‘iga ega multi-agent platforma. Xayoliy ma’lumotlarda jonli demo.",
            "h1": "Ark {Core}",
            "lead": "Vazifa bir marta qo‘yiladi. Keyin uni AI agentlar zanjiri olib boradi, inson esa faqat haqiqatan muhim narsani tasdiqlaydi.",
            "chain_title": "Vazifa qanday o‘tadi",
            "chain": ["Baholash", "Orkestrator", "Reja", "Bo‘lim rahbari", "Ijrochi", "Tekshiruv", "Qabul"],
            "demo_title": "O‘zingiz sinab ko‘ring",
            "demo_lead": "Bu xayoliy ma’lumotlardagi jonli demo. O‘ng pastdagi chatni oching va stsenariylardan birini ishga tushiring: oddiy savol, tijorat taklifi, bir necha bo‘limli vazifa yoki mijoz shikoyatini ko‘rib chiqish.",
            "demo_note": "Demo oldindan tayyorlangan stsenariylarda, tashqi AI xizmatlarisiz ishlaydi. Barcha kompaniyalar, bitimlar va summalar to‘qilgan.",
            "demo_open": "To‘liq ekranda ochish",
            "demo_loading": "Demo yuklanmoqda…",
            "features_title": "Ichida nima bor",
            "features": [
                {"t": "Bo‘limlar va rollar", "d": "Yuristlar, moliya, marketing, savdo. Vazifa hech bir bo‘limga mos kelmasa, platforma vaqtinchalik bo‘lim yaratadi."},
                {"t": "Aylanmada inson", "d": "Xato qimmatga tushadigan joyda jarayon haqiqatan to‘xtab, sizning qaroringizni kutadi."},
                {"t": "Bilimlar bazasi", "d": "Qidiruvli kompaniya bilimlar grafi. Agentlar faktlar va qoidalarni undan oladi."},
                {"t": "Xarajat hisobi", "d": "Har bir vazifada har bir qadamning tokenlari, narxi va kechikishi ko‘rinadi."},
                {"t": "Jurnal va huquqlar", "d": "Harakatlarning to‘liq auditi, foydalanuvchilar va kirish rollari."},
                {"t": "Telegram va Mini App", "d": "Vazifa qo‘yish va tasdiqlash to‘g‘ridan-to‘g‘ri messenjerdan."},
            ],
            "stack_title": "Texnologiyalar",
            "stack": ["Python", "JavaScript", "PostgreSQL + pgvector", "Redis", "Docker", "Telegram Bot API", "Lokal va bulutli LLM"],
            "cta": "Kompaniyangiz uchun shunday tizim kerakmi?",
        },
        "anton": {
            "slug": "anton",
            "name": "Anton",
            "tag": "AI agentlardan iborat avtonom IT-kompaniya",
            "short": "Bitta vazifa qo‘yasiz, uning ustida IT-kompaniya tuzilmasini takrorlaydigan agentlar iyerarxiyasi ishlaydi: dispetcherdan QA va relizgacha.",
            "title": "Anton — AI agentlardan iborat IT-kompaniya | hoolee",
            "description": "Anton: IT-kompaniya tuzilmasini takrorlaydigan avtonom AI agentlar orkestratsiya platformasi. Raundlar, tekshiruvchilar konsensusi, bilimlar bazasi va jonli izometrik ofis simulyatsiyasi.",
            "h1": "{Anton}",
            "lead": "Sizning boshqaruvingizdagi AI agentlardan iborat butun bir IT-kompaniya. Siz yuqori darajali vazifa qo‘yasiz, platforma ichida esa rollar ishlaydi: dispetcher, mahsulot, texnika, dizayn, ijrochilar, QA, xavfsizlik, reliz.",
            "org_title": "Tashkiliy tuzilma ish muhiti sifatida",
            "org": {"dispatcher": "Dispetcher", "cpo": "CPO · mahsulot", "cto": "CTO · texnika", "design": "Dizayn", "squad": "Ijrochilar jamoalari", "qa": "QA", "security": "Xavfsizlik", "release": "Reliz"},
            "org_lead": "Vazifa bir o‘tishda hal qilinmaydi. U iterativ raundlardan o‘tadi va majburiy tekshiruvchilar bir ovozdan ma’qullagandan yoki to‘xtash sharti ishlagandan keyingina tugaydi.",
            "features_title": "Asosiy g‘oyalar",
            "features": [
                {"t": "Raundlar va konsensus", "d": "Ish raundlarda boradi. “Tayyor” faqat barcha majburiy tekshiruvchilar ma’qullaganda qo‘yiladi."},
                {"t": "Tashkiliy xotira", "d": "Bilimlar grafi saboqlarni saqlaydi. Bir vazifada o‘rganilgan qoidalar boshqalariga qo‘shiladi."},
                {"t": "Ishonchlilik", "d": "Nosozlikdan keyin tiklanadigan hodisalar jurnali. Model noto‘g‘ri javobi hech qachon ma’qullash hisoblanmaydi."},
                {"t": "Byudjet himoyasi", "d": "Xarajat va so‘rov limitlari, qayta urinishlar, xatolar ketma-ketligida zanjirni uzish."},
                {"t": "Jonli simulyatsiya", "d": "Kim nima ustida ishlayotgani ko‘rinadigan izometrik ofis, shuningdek admin-panel va bilimlar grafi."},
                {"t": "Istalgan model", "d": "Bulutli va lokal modellar bilan yagona provayderlar qatlami orqali ishlaydi."},
            ],
            "status_title": "Holati",
            "status": "Alpha. C++ yadrosi ishlaydi, interfeyslar faol ishlab chiqilmoqda. Materiallar va namoyish so‘rov bo‘yicha.",
            "stack_title": "Texnologiyalar",
            "stack": ["C++20", "React", "PixiJS", "SQLite", "WebSocket", "Node.js", "Docker"],
            "cta": "Vazifangiz uchun agentlar orkestratsiyasi kerakmi?",
        },
    },
    "about": {
        "title": "hoolee studiyasi haqida — Toshkentda ishlanma va AI avtomatlashtirish",
        "description": "hoolee — Toshkentlik dasturchilar studiyasi. Biznes jarayonlarini avtomatlashtirish, AI agentlar va orkestratorlar, O‘zbekiston biznesi uchun tizimlar ishlab chiqish.",
        "h1": "{Odatiy ishni} avtomatik qiladigan studiya",
        "lead": "hoolee — Toshkentdagi dasturiy ishlanmalar studiyasi. Biz biznes jarayonlarini avtomatlashtiramiz va AI orkestratorlar yaratamiz. Har bir loyiha uchun kerakli profildagi dasturchilar jamoasini ulaymiz.",
        "story_title": "Biz qanday o‘ylaymiz",
        "story": [
            "Ko‘pchilik kompaniyalar vaqtni murakkab vazifalarga emas, o‘nlab mayda ishlarga yo‘qotadi: ma’lumotni ko‘chirish, eslatish, tekshirish, kelishish. Aynan ular eng yaxshi avtomatlashadi.",
            "Biz “AI uchun AI” sotmaymiz. Avval jarayonni tushunamiz, keyin vositani tanlaymiz: ba’zan oddiy skript yetadi, ba’zan agentlar zanjiri kerak.",
            "G‘oyalarimizni o‘z mahsulotlarimizda sinaymiz, shuning uchun tizimlar amalda qayerda buzilishini bilamiz.",
        ],
        "founder_title": "Asoschi",
        "founder_name": "Muhammadrizo Abdurazzoqov",
        "founder_role": "Software Engineer / ML Engineering / Data Science",
        "founder_text": "AI agent tizimlarini loyihalaydi va studiyaning har bir loyihasi arxitekturasi uchun javob beradi.",
        "founder_photo": "Surat tez orada",
        "values_title": "Nima bilan shug‘ullanamiz",
        "values": ["Jarayonlarni avtomatlashtirish", "AI orkestratorlar", "Tizimlar ishlab chiqish", "Joriy etish va qo‘llab-quvvatlash"],
    },
    "contact": {
        "title": "hoolee bilan bog‘lanish — avtomatlashtirish loyihasini muhokama qilish",
        "description": "hoolee studiyasiga ariza qoldiring: vazifangiz haqida ayting, birinchi qadamni taklif qilamiz. Toshkent, O‘zbekiston.",
        "h1": "{Vazifangiz} haqida ayting",
        "lead": "Nimani avtomatlashtirish kerakligi haqida bir-ikki gap. Ish vaqtida javob beramiz.",
        "location": "Toshkent, O‘zbekiston",
    },
    "form": {
        "title": "Biz bilan bog‘laning",
        "name": "Ism",
        "company": "Kompaniya",
        "contact": "Telefon yoki Telegram",
        "message": "Nimani avtomatlashtirish kerak?",
        "message_ph": "Masalan: menejerlar Telegramdagi arizalarni jadvalga qo‘lda ko‘chiradi…",
        "step2": "Qanday yuborasiz?",
        "step2_hint": "Qulay usulni tanlang. Tugmalardan birini bosmaguningizcha hech narsa yuborilmaydi.",
        "telegram": "Telegram orqali yuborish",
        "email": "Email orqali yuborish",
        "sending": "Yuborilmoqda…",
        "ok": "Ariza yuborildi. Siz bilan bog‘lanamiz.",
        "err": "Yuborib bo‘lmadi. Qayta urinib ko‘ring yoki boshqa usulni tanlang.",
        "required": "Ism, aloqa va vazifa tavsifini to‘ldiring.",
        "email_note": "Pochta dasturingiz tayyor xat bilan ochiladi.",
        "subject": "hoolee saytidan ariza",
    },
    "footer": {"pages": "Sahifalar", "contact": "Aloqa", "rights": "Barcha huquqlar himoyalangan"},
    "not_found": {"title": "Sahifa topilmadi", "text": "Bunday sahifa yo‘q. Bosh sahifaga qayting.", "home": "Bosh sahifa"},
}
